### ISSUE TITLE
This frozen actor has no footprint. Actor Name: srock05

### ISSUE THREAD

**Issue by yaaaaa** [cookgreen/Yuris-Revenge#80] opened 2019-09-08 09:17 UTC
OpenRA engine version release-20190314
Red Alert 2 Yuri's Revenge mod version playtest-20190825
on map 5132ba1eb1c6445f91a0134030ab2c9a0baf8343 (Hidden Valley by Westwood Studios).
Date: 2019-09-08 09:01:37Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.ArgumentException`: This frozen actor has no footprint.
Actor Name: srock05
Actor Location: 12,-12
Input footprint: []
Input footprint (after shroud.Contains): []
   в OpenRA.Traits.FrozenActor..ctor(Actor actor, ICreatesFrozenActors frozenTrait, PPos[] footprint, Player viewer, Boolean startsRevealed) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Traits\Player\FrozenActorLayer.cs:строка 94
   в OpenRA.Mods.Common.Traits.FrozenUnderFog.<>c__DisplayClass6.<OpenRA.Traits.INotifyCreated.Created>b__5(Player player, Int32 playerIndex) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Mods.Common\Traits\Modifiers\FrozenUnderFog.cs:строка 72
   в OpenRA.Primitives.PlayerDictionary`1..ctor(World world, Func`3 valueFactory) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Primitives\PlayerDictionary.cs:строка 38
   в OpenRA.Mods.Common.Traits.FrozenUnderFog.OpenRA.Traits.INotifyCreated.Created(Actor self) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Mods.Common\Traits\Modifiers\FrozenUnderFog.cs:строка 70
   в OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\World.cs:строка 272
   в OpenRA.World.CreateActor(String name, TypeDictionary initDict) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\World.cs:строка 265
   в OpenRA.Mods.Common.Traits.SpawnMapActors.WorldLoaded(World world, WorldRenderer wr) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Mods.Common\Traits\World\SpawnMapActors.cs:строка 41
   в OpenRA.World.LoadComplete(WorldRenderer wr) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\World.cs:строка 244
   в OpenRA.Game.StartGame(String mapUID, WorldType type) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 176
   в OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Network\UnitOrders.cs:строка 118
   в OpenRA.Network.OrderManager.TickImmediate() в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Network\OrderManager.cs:строка 133
   в OpenRA.Sync.<>c__DisplayClass5.<RunUnsynced>b__4() в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Sync.cs:строка 166
   в OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Sync.cs:строка 174
   в OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Sync.cs:строка 166
   в OpenRA.Game.InnerLogicTick(OrderManager orderManager) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 591
   в OpenRA.Game.LogicTick() в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 640
   в OpenRA.Game.Loop() в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 770
   в OpenRA.Game.Run() в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 810
   в OpenRA.Game.InitializeAndRun(String[] args) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 256
   в OpenRA.Program.Main(String[] args) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Support\Program.cs:строка 37

**Comment by cookgreen** [comment] 2019-09-09 03:36
Can't reproduce

**Comment by yaaaaa** [comment] 2019-09-09 12:40
OpenRA engine version release-20190314
Red Alert 2 Yuri's Revenge mod version playtest-20190825
on map 861cd5e3c0d54d407bfef3933b429860c12c84ad (Sovereign Land by Westwood Studios).
Date: 2019-09-09 12:33:46Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.ArgumentException`: This frozen actor has no footprint.
Actor Name: carus02d
Actor Location: 19,-12
Input footprint: []
Input footprint (after shroud.Contains): []
   в OpenRA.Traits.FrozenActor..ctor(Actor actor, ICreatesFrozenActors frozenTrait, PPos[] footprint, Player viewer, Boolean startsRevealed) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Traits\Player\FrozenActorLayer.cs:строка 94
   в OpenRA.Mods.Common.Traits.FrozenUnderFog.<>c__DisplayClass6.<OpenRA.Traits.INotifyCreated.Created>b__5(Player player, Int32 playerIndex) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Mods.Common\Traits\Modifiers\FrozenUnderFog.cs:строка 72
   в OpenRA.Primitives.PlayerDictionary`1..ctor(World world, Func`3 valueFactory) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Primitives\PlayerDictionary.cs:строка 38
   в OpenRA.Mods.Common.Traits.FrozenUnderFog.OpenRA.Traits.INotifyCreated.Created(Actor self) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Mods.Common\Traits\Modifiers\FrozenUnderFog.cs:строка 70
   в OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\World.cs:строка 272
   в OpenRA.World.CreateActor(String name, TypeDictionary initDict) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\World.cs:строка 265
   в OpenRA.Mods.Common.Traits.SpawnMapActors.WorldLoaded(World world, WorldRenderer wr) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Mods.Common\Traits\World\SpawnMapActors.cs:строка 41
   в OpenRA.World.LoadComplete(WorldRenderer wr) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\World.cs:строка 244
   в OpenRA.Game.StartGame(String mapUID, WorldType type) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 176
   в OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Network\UnitOrders.cs:строка 118
   в OpenRA.Network.OrderManager.TickImmediate() в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Network\OrderManager.cs:строка 133
   в OpenRA.Sync.<>c__DisplayClass5.<RunUnsynced>b__4() в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Sync.cs:строка 166
   в OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Sync.cs:строка 174
   в OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Sync.cs:строка 166
   в OpenRA.Game.InnerLogicTick(OrderManager orderManager) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 591
   в OpenRA.Game.LogicTick() в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 640
   в OpenRA.Game.Loop() в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 770
   в OpenRA.Game.Run() в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 810
   в OpenRA.Game.InitializeAndRun(String[] args) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 256
   в OpenRA.Program.Main(String[] args) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Support\Program.cs:строка 37

**Comment by cookgreen** [comment] 2019-09-12 04:34
> MustaphaTR
>  It is an engine issue, but you can as well remove the said actor, it is out of map anyway.

**Comment by cookgreen** [comment] 2020-03-11 13:54
can't reproduce, close it

**Closed by cookgreen** 2020-03-11 13:54 UTC
Labels: Bug, Can't reproduce, Engine Issue, Reopen
